### PR TITLE
Ignore rawread and usbid/regen binaries

### PR DESCRIPTION
**Pull request by nkovacs**

### CODE REVIEW

**Comment by zagrodzki** [comment]
interesting, it seems coveralls doesn't work with an encrypted token when a push comes from a forked repository... I'll have to check if there's any way around it...

In the meantime, I'm updating .travis.yml to skip coverage upload if token is not found...

**Comment by zagrodzki** [comment]
@nkovacs I've submitted #44, which should now make the tests pass. Coveralls doesn't work with forked repositories, sigh... Please merge updated master.

**Comment by zagrodzki** [comment]
@nkovacs still wrong, apparently. Pushed one more commit to get it right this time.. I hope? ;)

**Comment by nkovacs** [comment]
That's weird, I'm pretty sure I've seen coveralls work on pull requests before.

**Comment by nkovacs** [comment]
Maybe you need to add .coveralls.yml with `service_name: travis-ci`?

**Comment by zagrodzki** [comment]
yeah, so I'm not sure how it all fits together. But here's what I understand so far:
* travis encrypted vars are decrypted only if travis runs for the original repository, not a forked repository. So coveralls from a branch in kylelemons repo work, but for forks the env variable is not set.
* coveralls adivses  not to make the token public

There is a possibility that the repo token is not necessary at all for public github projects, I think coveralls can infer the project automatically. Maybe I was confused by the documentation... Let me check.

**Comment by nkovacs** [comment]
Yeah, I think you don't need to set the token in travis's env variables. I've checked one of our repos where this works, and there are no env variables in travis.

**Comment by zagrodzki** [comment]
@nkovacs done. Please merge again, and we should see coverage results if all works as expected, I suppose...

**Comment by zagrodzki** [comment]
yup, apparently it just works without the token. Oh well. I clearly got confused at some point when setting coverage reporting. Thanks for helping me sort it out.

**Comment by nkovacs** [comment]
No problem.

**Pull request merged**
