### PR TITLE
Libusb wrappers

### PR DESCRIPTION
**Pull request by zagrodzki**
This change moves all C-libusb-related functionality into a single libusb.go, wrapped in an interface.
I figured it would be best to do a very thin wrapper around C functionality that is not testable in Go, and then focus on testing higher level of abstractions with a fake libusb wrapper.

Tests were updated to use fakelibusb, a fake implementing the libusb interface.

This change will make it possible to test usb.go without actually interacting with the host USB stack.

### CODE REVIEW

**Comment by kylelemons** [comment]
I'm not sure I'm a fan of this.  Fundamentally, our whole library should be the thinnest possible wrapper around libusb so that callers, if necessary, can wrap it with their own.  If I were going to make an abstraction layer, I think I would actually do it on the C side.  Perhaps a fake libusb with enough fidelity that you can have a script that executes the go build command with the right ldflags to choose the fake library over the real one.  The fundamental problem with interposing an interface around all libusb calls is the overhead of making the call through the vtable; the extra vtable lookup and the thunk just adds to the the funcall (which is already noticeably slower due to cgo) and makes it even worse, and for performance-critical code (as you've seen with iso transfers) that overhead (and the additional stack it requires) can be difficult to work around later.

How much does this actually improve the testability of the package as a whole?  My impression as I was writing it, at least, was that making this sort of abstraction would mostly wind up encoding my expectations of libusb's behavior into my tests, rather than actually catching bugs.

**Comment by zagrodzki** [comment]
Benchmark results:
BenchmarkCGo/simple_function-4         	20000000	        75.3 ns/op
BenchmarkCGo/method-4                  	20000000	        75.1 ns/op
BenchmarkCGo/interface-4               	20000000	        79.7 ns/op

4ns is negligible even for low-latency audio applications.

**Comment by zagrodzki** [comment]
Case in point - I can't run a full suite of tests on travis, because libusb does not work in that environment...

**Comment by zagrodzki** [comment]
@kylelemons thoughts?

**Comment by kylelemons** [comment]
Oops, I thought I had replied already -- sure, I'm convinced :)

**Comment by zagrodzki** [comment]
good to go then?

**Pull request merged**
